name: Build Windows binaries
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ x64 ]
        include:
          - arch: x64
            platform: x64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ${{ matrix.arch }}
        shell: cmd
        run: |
          build.cmd ${{ matrix.platform }}

      - name: Archive artifact ${{ matrix.platform }}
        uses: actions/upload-artifact@v4
        with:
          name: Dark7z ${{ matrix.platform }}
          path: ${{ matrix.platform }}-bin
